//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartgeek.LogRotator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smartgeek.LogRotator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Access to ADSI denied. This program must be executed with elevated privileges..
        /// </summary>
        internal static string MsgAdsiAccessDenied {
            get {
                return ResourceManager.GetString("MsgAdsiAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        internal static string MsgCriticalException {
            get {
                return ResourceManager.GetString("MsgCriticalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string MsgEnd {
            get {
                return ResourceManager.GetString("MsgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Period = {1}, Format = {2}, Folder = {3}.
        /// </summary>
        internal static string MsgFolderInfo {
            get {
                return ResourceManager.GetString("MsgFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: folder not found.
        /// </summary>
        internal static string MsgFolderNotFound {
            get {
                return ResourceManager.GetString("MsgFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: skipping because custom logging is used.
        /// </summary>
        internal static string MsgFolderSkippedCustomLogging {
            get {
                return ResourceManager.GetString("MsgFolderSkippedCustomLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: skipping because logging is disabled.
        /// </summary>
        internal static string MsgFolderSkippedLoggingDisabled {
            get {
                return ResourceManager.GetString("MsgFolderSkippedLoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: skipping because compression and deletion are disabled.
        /// </summary>
        internal static string MsgFolderSkippedNoCompressionNoDeletion {
            get {
                return ResourceManager.GetString("MsgFolderSkippedNoCompressionNoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPSVC (7.5) feature not found.
        /// </summary>
        internal static string MsgFtpSvcFeatureFound {
            get {
                return ResourceManager.GetString("MsgFtpSvcFeatureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature found.
        /// </summary>
        internal static string MsgIisFeatureFound {
            get {
                return ResourceManager.GetString("MsgIisFeatureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature not found ({1}).
        /// </summary>
        internal static string MsgIisFeatureNotFound {
            get {
                return ResourceManager.GetString("MsgIisFeatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} compressed.
        /// </summary>
        internal static string MsgLogFileCompressed {
            get {
                return ResourceManager.GetString("MsgLogFileCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} compressing to {1}....
        /// </summary>
        internal static string MsgLogFileCompressing {
            get {
                return ResourceManager.GetString("MsgLogFileCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} compression error: {1}.
        /// </summary>
        internal static string MsgLogFileCompressionError {
            get {
                return ResourceManager.GetString("MsgLogFileCompressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        internal static string MsgLogFileDeleted {
            get {
                return ResourceManager.GetString("MsgLogFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleting (reason: {1})....
        /// </summary>
        internal static string MsgLogFileDeleting {
            get {
                return ResourceManager.GetString("MsgLogFileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deletion error: {1}.
        /// </summary>
        internal static string MsgLogFileDeletionError {
            get {
                return ResourceManager.GetString("MsgLogFileDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not compressed (simulation mode).
        /// </summary>
        internal static string MsgLogFileNotCompressedSimulationMode {
            get {
                return ResourceManager.GetString("MsgLogFileNotCompressedSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not deleted (simulation mode).
        /// </summary>
        internal static string MsgLogFileNotDeletedSimulationMode {
            get {
                return ResourceManager.GetString("MsgLogFileNotDeletedSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not overwriten (simulation mode).
        /// </summary>
        internal static string MsgLogFileNotOverwritenSimulationMode {
            get {
                return ResourceManager.GetString("MsgLogFileNotOverwritenSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} overwriten.
        /// </summary>
        internal static string MsgLogFileOverwriten {
            get {
                return ResourceManager.GetString("MsgLogFileOverwriten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: skipping {1} because it&apos;s the last log file.
        /// </summary>
        internal static string MsgLogFileSkippedLatest {
            get {
                return ResourceManager.GetString("MsgLogFileSkippedLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder read from IIS.
        /// </summary>
        internal static string MsgNoFolderToProcess {
            get {
                return ResourceManager.GetString("MsgNoFolderToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: no file to compress.
        /// </summary>
        internal static string MsgNoLogFileToCompress {
            get {
                return ResourceManager.GetString("MsgNoLogFileToCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: no file to delete.
        /// </summary>
        internal static string MsgNoLogFileToDelete {
            get {
                return ResourceManager.GetString("MsgNoLogFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing:.
        /// </summary>
        internal static string MsgProcessing {
            get {
                return ResourceManager.GetString("MsgProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0} legacy ADSI configuration....
        /// </summary>
        internal static string MsgReadingAdsiConfig {
            get {
                return ResourceManager.GetString("MsgReadingAdsiConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0} IIS Server Manager configuration....
        /// </summary>
        internal static string MsgReadingServerManagerConfig {
            get {
                return ResourceManager.GetString("MsgReadingServerManagerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite failed: This Windows Version must be NT 5.1 or newer (OSVersion = {0}).
        /// </summary>
        internal static string MsgRequireNewerWindows {
            get {
                return ResourceManager.GetString("MsgRequireNewerWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite failed: This program requires a Windows NT platform (PlatformID = {0}).
        /// </summary>
        internal static string MsgRequireWindowsNT {
            get {
                return ResourceManager.GetString("MsgRequireWindowsNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Access to IIS Server Manager denied. This program must be executed with elevated privileges..
        /// </summary>
        internal static string MsgServerManagerAccessDenied {
            get {
                return ResourceManager.GetString("MsgServerManagerAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Mode.
        /// </summary>
        internal static string MsgSimulationMode {
            get {
                return ResourceManager.GetString("MsgSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Version: {0}.
        /// </summary>
        internal static string MsgSummaryIisVersion {
            get {
                return ResourceManager.GetString("MsgSummaryIisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Version: {0}.
        /// </summary>
        internal static string MsgSummaryWindowsVersion {
            get {
                return ResourceManager.GetString("MsgSummaryWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown IIS version.
        /// </summary>
        internal static string MsgUnknownIisVersionString {
            get {
                return ResourceManager.GetString("MsgUnknownIisVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Windows versions newer than NT 6.2 were never been tested. Please report any problem..
        /// </summary>
        internal static string MsgUnknownWindowsVersion {
            get {
                return ResourceManager.GetString("MsgUnknownWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} to process:.
        /// </summary>
        internal static string MsgXFoldersToProcess {
            get {
                return ResourceManager.GetString("MsgXFoldersToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} compressed, {2} deleted.
        /// </summary>
        internal static string MsgXLogFilesCompressedXDeleted {
            get {
                return ResourceManager.GetString("MsgXLogFilesCompressedXDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} {2} deleted.
        /// </summary>
        internal static string MsgXLogFilesDeleted {
            get {
                return ResourceManager.GetString("MsgXLogFilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} {2} to compress....
        /// </summary>
        internal static string MsgXLogFilesToCompress {
            get {
                return ResourceManager.GetString("MsgXLogFilesToCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} {2} to delete....
        /// </summary>
        internal static string MsgXLogFilesToDelete {
            get {
                return ResourceManager.GetString("MsgXLogFilesToDelete", resourceCulture);
            }
        }
    }
}
