//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartgeek.LogRotator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smartgeek.LogRotator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Access to ADSI denied. This program must be executed with elevated privileges..
        /// </summary>
        internal static string MsgAdsiAccessDenied {
            get {
                return ResourceManager.GetString("MsgAdsiAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        internal static string MsgCriticalException {
            get {
                return ResourceManager.GetString("MsgCriticalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string MsgEnd {
            get {
                return ResourceManager.GetString("MsgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPSVC (7.5) feature not found.
        /// </summary>
        internal static string MsgFtpSvcFeatureFound {
            get {
                return ResourceManager.GetString("MsgFtpSvcFeatureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature found.
        /// </summary>
        internal static string MsgIisFeatureFound {
            get {
                return ResourceManager.GetString("MsgIisFeatureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feature not found ({1}).
        /// </summary>
        internal static string MsgIisFeatureNotFound {
            get {
                return ResourceManager.GetString("MsgIisFeatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder read from IIS.
        /// </summary>
        internal static string MsgNoFolderToProcess {
            get {
                return ResourceManager.GetString("MsgNoFolderToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing:.
        /// </summary>
        internal static string MsgProcessing {
            get {
                return ResourceManager.GetString("MsgProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0} legacy ADSI configuration....
        /// </summary>
        internal static string MsgReadingAdsiConfig {
            get {
                return ResourceManager.GetString("MsgReadingAdsiConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0} IIS Server Manager configuration....
        /// </summary>
        internal static string MsgReadingServerManagerConfig {
            get {
                return ResourceManager.GetString("MsgReadingServerManagerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite failed: This Windows Version must be NT 5.1 or newer (OSVersion = {0}).
        /// </summary>
        internal static string MsgRequireNewerWindows {
            get {
                return ResourceManager.GetString("MsgRequireNewerWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite failed: Must be a Windows NT platform (PlatformID = {0}).
        /// </summary>
        internal static string MsgRequireWindowsNT {
            get {
                return ResourceManager.GetString("MsgRequireWindowsNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Access to IIS Server Manager denied. This program must be executed with elevated privileges..
        /// </summary>
        internal static string MsgServerManagerAccessDenied {
            get {
                return ResourceManager.GetString("MsgServerManagerAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Mode.
        /// </summary>
        internal static string MsgSimulationMode {
            get {
                return ResourceManager.GetString("MsgSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Version: {0}.
        /// </summary>
        internal static string MsgSummaryIisVersion {
            get {
                return ResourceManager.GetString("MsgSummaryIisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Version: {0}.
        /// </summary>
        internal static string MsgSummaryWindowsVersion {
            get {
                return ResourceManager.GetString("MsgSummaryWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown IIS version.
        /// </summary>
        internal static string MsgUnknownIisVersionString {
            get {
                return ResourceManager.GetString("MsgUnknownIisVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Windows versions newer than NT 6.2 were never been tested. Please report any problem..
        /// </summary>
        internal static string MsgUnknownWindowsVersion {
            get {
                return ResourceManager.GetString("MsgUnknownWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} to process:.
        /// </summary>
        internal static string MsgXFoldersToProcess {
            get {
                return ResourceManager.GetString("MsgXFoldersToProcess", resourceCulture);
            }
        }
    }
}
